[package]
name = "mokumoku"
version = "0.1.0"
authors = ["aoyagikouhei <aoyagi.kouhei@gmail.com>"]

[dependencies]
futures = "~0.1"
hyper = "~0.11"
gotham = "~0.2"
gotham_derive = "~0.2"
mime = "~0.3"
serde = "*"
serde_json = "*"
serde_derive = "*"
r2d2 = "*"
r2d2_redis = "*"
redis = "*"